
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfe
  template:
    metadata:
      labels:
        app: pfe
    spec:
      containers:
      - name: pfe
        image: Abde1ilah/pfe:latest
        ports:
        - containerPort: 8080  # Change to your app's port if different

---

apiVersion: v1
kind: Service
metadata:
  name: pfe-service
spec:
  selector:
    app: pfe
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080  # Change if your container uses a different port
  type: LoadBalancer  # Use NodePort for minikube or local clusters
